dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
wallets:
  from_key: ${PRIVATE_KEY}